attenadnce_system_dsg/urls.py
from django.contrib import admin
from django.urls import path, include
from members.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('', include('accounts.urls')),
    path('', include('members.urls')),
    path('', include('attendance.urls')),

]

members/urls.py
from django.urls import path
from . import views

app_name = 'members'

urlpatterns = [
    path('', views.home, name='home'),
    path('members/', views.memberList, name='members'),
    path('members/<int:id>/', views.viewMember, name='viewMember'),
    path('add_member/', views.addMember, name='addMember'),
    path('edit_member/<int:id>/', views.editMember, name='editMember'),
    path('delete_member/<int:id>/', views.deleteMember, name='deleteMember'),
]

attendance/models.py
from django.db import models
from members.models import Members

class Event(models.Model):
    eventName = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.eventName

class Attendance(models.Model):
    member = models.ForeignKey(Members, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.member.firstName} {self.member.lastName} attended {self.event.eventName}"

members/models.py
from django.db import models
import qrcode
from io import BytesIO
from django.core.files import File
from django.core.validators import RegexValidator
from django.conf import settings
from PIL import Image, ImageDraw

# Programs
CAS = 'CAS'
CCS = 'CCS'
CEA = 'CEA'

# SCHOLARSHIP TYPES
MERIT = 'Merit'
JLSS_MERIT = 'JLSS Merit'
RA_7687 = 'RA 7687'
JLSS_RA_7687 = 'JLSS RA 7687'
RA_10612 = 'RA 10612'


class Members(models.Model):
    
    OFFICER = 'Officer'
    MEMBER = 'Member'

    ROLE_CHOICES = [
        (OFFICER, 'Officer'),
        (MEMBER, 'Member'),
    ]

    studentNumber = models.PositiveIntegerField()
    firstName = models.CharField(max_length=50)
    middleName = models.CharField(max_length=50)
    lastName = models.CharField(max_length=50)
    program_and_year = models.CharField(max_length=20)
    college = models.CharField(max_length=3, choices=[(CAS, 'CAS'), (CCS, 'CCS'), (CEA, 'CEA')])
    scholarshipType = models.CharField(max_length=20, choices=[(MERIT, 'Merit'), (JLSS_MERIT, 'JLSS Merit'), (RA_7687, 'RA 7687'), (JLSS_RA_7687, 'JLSS RA 7687'), (RA_10612, 'RA 10612')])
    cpNum = models.CharField(max_length=12, validators=[RegexValidator(r'^\d{1,12}$')], blank=True)
    personalEmail = models.EmailField()
    cspcEmail = models.EmailField()
    address = models.CharField(max_length=100)
    position = models.CharField(max_length=50, blank=True)
    role = models.CharField(max_length=10, choices=ROLE_CHOICES, default=MEMBER)
    qr_code = models.ImageField(upload_to='qr_codes/', blank=True)

    def __str__(self):
        return f'Member: {self.firstName} {self.middleName} {self.lastName}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        # Use a fixed URL path that will redirect dynamically
        qr_code_url = f"/qr-redirect/{self.studentNumber}/"
        qr_image = qrcode.make(qr_code_url)
        canvas = Image.new('RGB', (qr_image.size), 'white')
        canvas.paste(qr_image)
        buffer = BytesIO()
        canvas.save(buffer, 'PNG')
        self.qr_code.save(f'qr_code_{self.studentNumber}.png', File(buffer), save=False)

members/forms.py
from django import forms
from .models import Members

class MembersForm(forms.ModelForm):
    class Meta:
        model = Members
        fields = ['studentNumber', 'firstName', 'middleName', 'lastName', 'program_and_year', 'college', 'scholarshipType', 'cpNum', 'personalEmail', 'cspcEmail', 'address', 'position']
        labels = {
            'studentNumber': 'Student No.',
            'firstName': 'First Name',
            'middleName': 'Middle Name',
            'lastName': 'Last Name',
            'program_and_year': 'Degree, Program & Year Level',
            'college': 'College/Unit',
            'scholarshipType': 'Scholarship Type',
            'cpNum': 'Contact No.',
            'personalEmail': 'Personal Email',
            'cspcEmail': 'CSPC Email',
            'address': 'Home Address',
            'position': 'Position',
        }
        widgets = {
            'studentNumber': forms.NumberInput(attrs={'class': 'form-control'}),
            'firstName': forms.TextInput(attrs={'class': 'form-control'}),
            'middleName': forms.TextInput(attrs={'class': 'form-control'}),
            'lastName': forms.TextInput(attrs={'class': 'form-control'}),
            'program_and_year': forms.TextInput(attrs={'class': 'form-control'}),
            'college': forms.Select(attrs={'class': 'form-control'}),
            'scholarshipType': forms.Select(attrs={'class': 'form-control'}),
            'cpNum': forms.TextInput(attrs={'class': 'form-control'}),
            'personalEmail': forms.EmailInput(attrs={'class': 'form-control'}),
            'cspcEmail': forms.EmailInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'position': forms.TextInput(attrs={'class': 'form-control'}),
        }

members/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib import messages
from django.db import IntegrityError
from django.template.loader import render_to_string
from .models import Members
from .forms import MembersForm
from attendance.models import *
from django.contrib.auth.decorators import login_required
from common.decorators import *


# Create your views here.
@login_required
def home(request):
    return render(request, 'home.html')

@officer_required
def memberList(request):
    return render(request, 'members/memberList.html', {'members': Members.objects.all()})

@officer_required
def viewMember(request, event_id):
    member = Members.objects.get(pk=id)
    event = get_object_or_404(event, id=event_id)
    attendance = Attendance.objects.filter(event=event)

    events_attended = request.GET.get('attendance')
    return render(request, 'members/memberList.html', {
        'member': member,
        'event': event,
        'attendance': attendance,
        'events_attended': events_attended,
    })

@officer_required
def addMember(request):
    if request.method == 'POST':
        form = MembersForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                member = form.save(commit=False)
                member.save()
                messages.success(request, f"Member: {member.firstName} {member.lastName} has been added successfully!")
            except IntegrityError:
                messages.error(request, 'Failed to add member.')
            return redirect('members:members')
    else:
        form = MembersForm()

    return render(request, 'members/addMember.html', {'form': form})
    
@officer_required
def editMember(request, id):
    member = Members.objects.get(pk=id)
    if request.method == 'POST':
        form = MembersForm(request.POST, request.FILES, instance=member)
        if form.is_valid():
            form.save()
            messages.success(request, f"Member: {member.firstName} {member.middleName} {member.lastName} has been updated successfully!")
            return redirect('members:members')
    else:
        form = MembersForm(instance=member)

    context = {
        'form': form,
        'member': member
    }

    html_form = render_to_string('members/editMember.html', context, request=request)
    return JsonResponse({'html_form': html_form})

@officer_required
def deleteMember(request, id):
    if request.method == 'POST':
        member = Members.objects.get(pk=id)
        member.delete()
        messages.success(request, f"Member: {member.firstName} {member.middleName} {member.lastName} has been deleted successfully!")
    return HttpResponseRedirect(reverse('members:members'))

templates/members/addMember.html
{% block index %}

    <h3 class="text-center m-4"></h3>
        <div class="row justify-content-center">
            <div class="col-6">
                <div class="card bg-light mb-3">
                    <div class="card-header">
                        <i class="fa-solid fa-address-card fa-lg"> Member Registration</i>
                    </div>
                    <div class="card-body">
                        <form action="{% url 'members:addMember' %}" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Add</button>
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                        </form>
                    </div>
                  </div>
            </div>
        </div>


{% endblock %}

templates/members/editMember.html
{% block index %}

        <div class="row justify-content-center">
            <div class="col-6">
                <div class="card bg-light mb-3">
                    <div class="card-header">
                        <i class="fa-solid fa-pen-to-square fa-lg"> Update Member Record(s)</i>
                    </div>
                    <div class="card-body">
                        <form action="{% url 'members:editMember' member.id %}" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Update</button>
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                        </form>
                    </div>
                  </div>
            </div>
        </div>

{% endblock %}

templates/members/memberList.html
{% extends "index.html" %}

{% block index %}
{% include 'navbar.html' %}

<div class="container-fluid">
    <div class="row">
      <div class="col-6">
      <h3 class="m-4 d-inline-block" style="color: white;">All Members</h3>
      </div>
      <div class="col-6 text-end">
        <button type="button" class="btn btn-primary m-4" id="addMemberButton">Add Member</button>
      </div>      
      <div class="col-12">
        {% if members %}
          <div class="card border-danger ms-4 me-4 mb-4">
            <div class="card-header">
              <i class="fa-solid fa-user-graduate fa-lg"></i> Members Records
            </div>
            <div class="card-body">
              <p class="card-text">
                <div class="table-responsive">
                  <table class="table table-hover">
                    <thead>
                      <tr>
                        <th scope="col">Student No.</th>
                        <th scope="col">Name</th>
                        <th scope="col">Degree, Program & Year Level</th>
                        <th scope="col">College/Unit</th>
                        <th scope="col">Scholarship Type</th>
                        <th scope="col">Contact No.</th>
                        <th scope="col">Personal Email</th>
                        <th scope="col">CSPC Email</th>
                        <th scope="col">Home Address</th>
                        <th scope="col">Position</th>
                        <th scope="col">Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for members in members %}
                        <tr>
                          <td>{{ members.studentNumber }}</td>
                          <td>{{ members.firstName }} {{ members.middleName }} {{ members.lastName }}</td>
                          <td>{{ members.program_and_year }}</td>
                          <td>{{ members.college }}</td>
                          <td>{{ members.scholarshipType }}</td>
                          <td>{{ members.cpNum }}</td>
                          <td>{{ members.personalEmail }}</td>
                          <td>{{ members.cspcEmail }}</td>
                          <td>{{ members.address }}</td>
                          <td>{{ members.position }}</td>
                          <td>
                            <button class="btn btn-success me-1" href="{% url 'members:members' %}" data-bs-toggle="modal" data-bs-target="#myModal{{members.id}}">
                              <i class="fa-solid fa-circle-info fa-lg"></i>
                            </button>

                            <!-- Modal - View Events Attended -->
                            <div class="modal" id="myModal{{members.id}}" tabindex="-1" aria-labelledby="myModalLabel1" aria-hidden="true">
                              <div class="modal-dialog modal-lg" role="document">
                                <div class="modal-content">
                                  <div class="modal-header">
                                    <h5 class="modal-title">Member: {{ members.firstName }} {{ members.middleName }} {{ members.lastName }}</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                  </div>
                                  <div class="modal-body">
                                    <ul class="list-unstyled">
                                      <li>Events Attended:</li>
                                      <ul>
                                        {% for attendance in members.attendance_set.all %}
                                          <li>{{ attendance.event.eventName }} on {{ attendance.timestamp }}</li>
                                        {% empty %}
                                          <li>No events attended.</li>
                                        {% endfor %}
                                      </ul>
                                    </ul>
                                  </div>
                                  <div class="modal-footer">
                                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
                                  </div>
                                </div>
                              </div>
                            </div>


                            <!-- Edit Member Modal -->
                            <button type="button" class="btn btn-warning me-1 editMemberButton" data-bs-toggle="modal" data-bs-target="#edit{{members.id}}" data-member-id="{{ members.id }}">
                              <i class="fa-solid fa-pen-to-square fa-lg"></i>
                            </button>

                            <div class="modal fade" role="dialog" id="edit{{members.id}}" tabindex="-1" aria-labelledby="editMemberModalLabel" aria-hidden="true">
                              <div class="modal-dialog modal-xl">
                                <div class="modal-content">
                                  <div class="modal-header">
                                  <h5 class="modal-title" id="editMemberModalLabel">Update Member</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                  </div>
                                  <div class="modal-body">
                                      <!-- Form content will be loaded here -->
                                  </div>
                                </div>
                              </div>
                            </div>
                          
                                                                                
                            <script>
                              document.addEventListener('DOMContentLoaded', function() {
                                const editMemberButtons = document.querySelectorAll('.editMemberButton');
                                editMemberButtons.forEach(button => {
                                    button.addEventListener('click', function() {
                                        const memberId = button.getAttribute('data-member-id');
                                        fetch(`/edit_member/${memberId}/`)
                                            .then(response => response.json())
                                            .then(data => {
                                                const modal = document.getElementById(`edit${memberId}`);
                                                modal.querySelector('.modal-body').innerHTML = data.html_form;
                                            });
                                    });
                                });
                            });
                            </script>

                            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#delete{{members.id}}">
                              <i class="fa-solid fa-trash-can fa-lg"></i>
                            </button>

                            <!-- Modal - Delete Member -->
                            <div class="modal fade" id="delete{{members.id}}" tabindex="-1" aria-labelledby="deleteMemberModalLabel" aria-hidden="true">
                              <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                  <div class="modal-header">
                                    <h5 class="modal-title">
                                      Member: {{ members.firstName }} {{ members.middleName }} {{ members.lastName }}
                                    </h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                                      <span aria-hidden="true"></span>
                                    </button>
                                  </div>
                                  <div class="modal-body">
                                    <p>Are you sure you want to delete this member?</p>
                                  </div>
                                  <div class="modal-footer">
                                    <form action="{% url 'members:deleteMember' members.id %}" method="POST">
                                      {% csrf_token %}
                                      <input type="submit" class="btn btn-primary" value="Delete">
                                    </form>
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                  </div>
                                </div>
                              </div>
                            </div>

                          </td>
                        </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </p>
            </div>
          </div>
        {% else %}
          <h5 class="alert alert-primary ms-4 me-4">No Records.</h5>
        {% endif %}

<!-- Add Member Modal -->
<div class="modal fade" id="addMemberModal" tabindex="-1" aria-labelledby="addMemberModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl"> <!-- Add 'modal-lg' class here -->
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addMemberModalLabel">Add a member</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="addMemberModalBody">
        <!-- Form content will be loaded here -->
      </div>
    </div>
  </div>
</div>


<script>
  document.addEventListener('DOMContentLoaded', function() {
    const addMemberModal = new bootstrap.Modal(document.getElementById('addMemberModal'));

    document.getElementById('addMemberButton').addEventListener('click', function() {
      fetch("{% url 'members:addMember' %}")
        .then(response => response.text())
        .then(html => {
          document.getElementById('addMemberModalBody').innerHTML = html;
          addMemberModal.show();
        });
    });
  });
</script>

{% endblock %}